name: Mi Primer Workflow
on: workflow_dispatch
jobs: 
  mi-primer-job:
    runs-on: ubuntu-latest
    steps: 
    - name: Imprimir Saludo
      run: echo "Hola Mundo con Github Actions"
    - name: Imprimir Despedida
      run: echo "Listo, ¡Adios!"
